[project]
name = "consola"
version = "0.1.0"
description = "An Interactive SQL Console for interacting database models using SQLAlchemy or SQLModel in Python"
license = "MIT"
readme = "README.md"
authors = [{ name = "Daniel Brai", email = "danielbrai.dev@gmail.com" }]
keywords = ["sql", "console", "interactive", "sqlalchemy"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "Operating System :: POSIX :: Linux",
    "Topic :: Utilities",
    "Topic :: Database",
]
requires-python = ">=3.11"
dependencies = [
    "sqlalchemy==2.0.46",
    "sqlmodel==0.0.33",
    "typer>=0.24.1",
]

[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["pre-commit>=4.5.1"]


[project.urls]
Homepage = "https://github.com/Daniel-Brai/Consola"
Repository = "https://github.com/Daniel-Brai/Consola"
Source = "https://github.com/Daniel-Brai/Consola"
Issues = "https://github.com/Daniel-Brai/Consola/issues"


[project.scripts]
consola = "consola:main"

[tool.uv]
package = true

[tool.bandit]
severity_level = "HIGH"
confidence_level = "HIGH"
exclude_dirs = ["tests", "venv", ".venv", "build", "dist", "__pycache__", "examples"]

[tool.mypy]
python_version = "3.10"
show_error_codes = true
warn_unused_configs = true
check_untyped_defs = true
implicit_optional = true
exclude = ["^./build/.*$", "^./.venv/.*$", "^.*/tests/.*$", "^./examples/.*$"]


[tool.ruff.lint]
select = [
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings
    "F",      # pyflakes
    "I",      # isort
    "B",      # flake8-bugbear
    "C4",     # flake8-comprehensions
    "UP",     # pyupgrade
]
ignore = [
    "E501", # line too long, handled by black
    "B008", # do not perform function calls in argument defaults
    "W191", # indentation contains tabs
    "C416", # Allow use of list comprehensions
]
